@hostname = http://{{$dotenv HOST}}
@port = {{$dotenv PORT}}
@baseURL = {{hostname}}:{{port}}

###
# Get the footer contents

GET {{baseURL}}/api/footer?populate=*
Authorization: Bearer {{$dotenv API_TOKEN}}
